export const WORKER_EVENTS = {
  PORT_INIT: "PORT_INIT",
  RUN_BIG_TASK: "RUN_BIG_TASK",
  SEND_EVENT: "SEND_EVENT",
  SEND_MAYHEM_EVENT: "SEND_MAYHEM_EVENT",
  INPUT_QUEUE: "INPUT_QUEUE",
  INPUT_MAYHEM_QUEUE: "INPUT_MAYHEM_QUEUE",
  RECIEVE_EVENT: "RECIEVE_EVENT",
};
